def load_settings():
    # ...existing code...
    print("Loading settings")
    # ...existing code...

def save_settings():
    # ...existing code...
    print("Saving settings")
    # ...existing code...
